gui:
  windowSize: 'normal' # one of 'normal' | 'half' | 'full' default is 'normal'
  nerdFontsVersion: "3" # 2 or 3
  skipDiscardChangeWarning: true
  theme:
    activeBorderColor:
      - '#C8C093'
      - bold
    inactiveBorderColor:
      - '#836f4a'
    searchingActiveBorderColor:
      - '#EEC843'
      - bold
    optionsTextColor:
      - '#4d699b'
    selectedLineBgColor:
      - '#8a8980'
    selectedRangeBgColor:
      - '#545464'
    cherryPickedCommitBgColor:
      - '#4d699b'
    cherryPickedCommitFgColor:
      - '#6693bf'
    unstagedChangesColor:
      - '#e82424'
    defaultFgColor:
      - '#DCD7BA'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false
os:
  editInTerminal: true
  editPreset: 'vscode' # vscode, nvim
