# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json
notARepository: 'skip'
gui:
  windowSize: "normal" # one of 'normal' | 'half' | 'full' default is 'normal'
  nerdFontsVersion: "3" # 2 or 3
  skipDiscardChangeWarning: true
  sidePanelWidth: 0.3
  expandFocusedSidePanel: true
  theme:
    activeBorderColor:
      - "#f9c859"
      - bold
    inactiveBorderColor:
      - "#3476ff"
    searchingActiveBorderColor:
      - "#EEC843"
      - bold
    optionsTextColor:
      - "#5fb9bc"
    selectedLineBgColor:
      - "#41444d"
    cherryPickedCommitBgColor:
      - "#4483aa"
    cherryPickedCommitFgColor:
      - "#f9c859"
    unstagedChangesColor:
      - "#fc2f52"
    defaultFgColor:
      - "#3476ff"
  border: 'rounded' # 'double'
  showRandomTip: false
  showBottomLine: false
git:
  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 72
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false
  autoFetch: true
  autoRefresh: true
os:
  editInTerminal: false
  editPreset: "vscode" # vscode, nvim
refresher:
  fetchInterval: 60 # Re-fetch interval in seconds. Auto-fetch can be disabled via option 'git.autoFetch'.
  refreshInterval: 10 # File/submodule refresh interval in seconds. Auto-refresh can be disabled via option 'git.autoRefresh'.
keybinding:
  universal:
    togglePanel: "<tab>"
    nextTab: "<Right>"
    prevTab: "<Left>"
    prevBlock: ""
    nextBlock: ""
