gui:
  windowSize: "normal" # one of 'normal' | 'half' | 'full' default is 'normal'
  nerdFontsVersion: "3" # 2 or 3
  skipDiscardChangeWarning: true
  theme:
    activeBorderColor:
      - "#f9c859"
      - bold
    inactiveBorderColor:
      - "#3476ff"
    searchingActiveBorderColor:
      - "#EEC843"
      - bold
    optionsTextColor:
      - "#5fb9bc"
    selectedLineBgColor:
      - "#41444d"
    cherryPickedCommitBgColor:
      - "#4483aa"
    cherryPickedCommitFgColor:
      - "#f9c859"
    unstagedChangesColor:
      - "#fc2f52"
    defaultFgColor:
      - "#3476ff"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false
os:
  editInTerminal: true
  editPreset: "vscode" # vscode, nvim
keybinding:
  universal:
    togglePanel: "<tab>"
    nextTab: "<Right>"
    prevTab: "<Left>"
    prevBlock: ""
    nextBlock: ""
