gui:
  windowSize: 'normal' # one of 'normal' | 'half' | 'full' default is 'normal'
  nerdFontsVersion: "3" # 2 or 3
  skipDiscardChangeWarning: true
  theme:
    activeBorderColor:
      - '#c5c9c5'
      - bold
    inactiveBorderColor:
      - '#43436c'
    searchingActiveBorderColor:
      - '#EEC843'
      - bold
    optionsTextColor:
      - '#E6C384'
    selectedLineBgColor:
      - '#363646'
    selectedRangeBgColor:
      - '#c5c9c5'
    cherryPickedCommitBgColor:
      - '#EEC843'
    cherryPickedCommitFgColor:
      - '#545464'
    unstagedChangesColor:
      - '#e82424'
    defaultFgColor:
      - '#938AA9'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false
os:
  editInTerminal: true
  editPreset: 'vscode' # vscode, nvim
keybinding:
  universal:
    nextTab: '<Right>'
    prevTab: '<Left>'
    prevBlock: ''
    nextBlock: ''